# Generated by Django 5.2.4 on 2025-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_event_galleryimage_pricingplan_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='event',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Article featured image', null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event image/icon', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, help_text='Solution image/icon', null=True, upload_to='solutions/'),
        ),
    ]
